steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t', 'gcr.io/$PROJECT_ID/wigoh_hrms/attendance-tracker',
           '-f', 'Dockerfile',
           '--build-arg', 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID',  # Specify the Dockerfile path
           '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'gcr.io/$PROJECT_ID/wigoh_hrms/attendance-tracker']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy',
           'attendance-tracker',
           '--image', 'gcr.io/$PROJECT_ID/wigoh_hrms/attendance-tracker',
           '--region', 'us-central1',
           '--platform', 'managed',
           '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/wigoh_hrms/attendance-tracker'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'
